// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1K2ptaLl3gy7kn48YB2Mh9f2kpaAvprk',
    appId: '1:823909917987:web:fd5510ff85f8f4809b9896',
    messagingSenderId: '823909917987',
    projectId: 'practice-debfe',
    authDomain: 'practice-debfe.firebaseapp.com',
    storageBucket: 'practice-debfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8pkwDpNX1nQfIgOBkUGjzx_dJx5q6Sg',
    appId: '1:823909917987:android:2144e96cf1ded8199b9896',
    messagingSenderId: '823909917987',
    projectId: 'practice-debfe',
    storageBucket: 'practice-debfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zln1y8nJlQSnX2z-CA-i_IiRs2cKH6U',
    appId: '1:823909917987:ios:0fa7fbe28eb3597a9b9896',
    messagingSenderId: '823909917987',
    projectId: 'practice-debfe',
    storageBucket: 'practice-debfe.appspot.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
